[package]
name = "exalted"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25"
rusttype = "0.9"
softbuffer = "0.4"
taffy = { version = "0.5", features = [ "grid", "flexbox" ] }
tiny-skia = "0.11"
winit = "0.30"
